/*
 * Hogwarts.Api.NetMinimalApi | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class HogwartsApiNetMinimalApiApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/students")]
        [ValidateModelState]
        [SwaggerOperation("GetStudents")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Student>), description: "OK")]
        public virtual IActionResult GetStudents()
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Student>));
            string exampleJson = null;
            exampleJson = "[ {\r\n  \"firstName\" : \"firstName\",\r\n  \"surname\" : \"surname\",\r\n  \"id\" : 0,\r\n  \"fullname\" : \"fullname\"\r\n}, {\r\n  \"firstName\" : \"firstName\",\r\n  \"surname\" : \"surname\",\r\n  \"id\" : 0,\r\n  \"fullname\" : \"fullname\"\r\n} ]";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<Student>>(exampleJson)
            : default(List<Student>);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
