openapi: 3.0.1
info:
  title: Hogwarts.Api.NetMinimalApi | v1
  version: 1.0.0
servers:
  - url: http://localhost:5280
paths:
  /students:
    get:
      tags:
        - Hogwarts.Api.NetMinimalApi
      operationId: GetStudents
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Student"
components:
  schemas:
    Student:
      required:
        - id
        - firstName
        - surname
      type: object
      properties:
        id:
          type: integer
          format: int32
        firstName:
          type: string
        surname:
          type: string
        fullname:
          type: string
          nullable: true
tags:
  - name: Hogwarts.Api.NetMinimalApi
